-- Add the column if it doesn't exist (safety check)
ALTER TABLE champions ADD COLUMN IF NOT EXISTS lanes text[] DEFAULT '{}';

-- Update lanes for all champions (Strict: Max 2 lanes, 'Bot' -> 'Adc')

UPDATE champions SET lanes = ARRAY['Top'] WHERE name = 'Aatrox';
UPDATE champions SET lanes = ARRAY['Mid'] WHERE name = 'Ahri';
UPDATE champions SET lanes = ARRAY['Mid', 'Top'] WHERE name = 'Akali';
UPDATE champions SET lanes = ARRAY['Mid', 'Top'] WHERE name = 'Akshan';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Alistar';
UPDATE champions SET lanes = ARRAY['Jungle', 'Support'] WHERE name = 'Amumu';
UPDATE champions SET lanes = ARRAY['Mid', 'Support'] WHERE name = 'Anivia';
UPDATE champions SET lanes = ARRAY['Mid', 'Support'] WHERE name = 'Annie';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Aphelios';
UPDATE champions SET lanes = ARRAY['Adc', 'Support'] WHERE name = 'Ashe';
UPDATE champions SET lanes = ARRAY['Mid'] WHERE name = 'Aurelion Sol';
UPDATE champions SET lanes = ARRAY['Mid'] WHERE name = 'Azir';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Bard';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Bel''Veth';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Blitzcrank';
UPDATE champions SET lanes = ARRAY['Support', 'Jungle'] WHERE name = 'Brand';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Braum';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Briar';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Caitlyn';
UPDATE champions SET lanes = ARRAY['Top', 'Support'] WHERE name = 'Camille';
UPDATE champions SET lanes = ARRAY['Mid', 'Top'] WHERE name = 'Cassiopeia';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Cho''Gath';
UPDATE champions SET lanes = ARRAY['Adc', 'Mid'] WHERE name = 'Corki';
UPDATE champions SET lanes = ARRAY['Top'] WHERE name = 'Darius';
UPDATE champions SET lanes = ARRAY['Jungle', 'Mid'] WHERE name = 'Diana';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Draven';
UPDATE champions SET lanes = ARRAY['Top', 'Jungle'] WHERE name = 'Dr. Mundo';
UPDATE champions SET lanes = ARRAY['Jungle', 'Mid'] WHERE name = 'Ekko';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Elise';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Evelynn';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Ezreal';
UPDATE champions SET lanes = ARRAY['Jungle', 'Support'] WHERE name = 'Fiddlesticks';
UPDATE champions SET lanes = ARRAY['Top'] WHERE name = 'Fiora';
UPDATE champions SET lanes = ARRAY['Mid'] WHERE name = 'Fizz';
UPDATE champions SET lanes = ARRAY['Mid', 'Support'] WHERE name = 'Galio';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Gangplank';
UPDATE champions SET lanes = ARRAY['Top'] WHERE name = 'Garen';
UPDATE champions SET lanes = ARRAY['Top'] WHERE name = 'Gnar';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Gragas';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Graves';
UPDATE champions SET lanes = ARRAY['Top', 'Jungle'] WHERE name = 'Gwen';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Hecarim';
UPDATE champions SET lanes = ARRAY['Support', 'Top'] WHERE name = 'Heimerdinger';
UPDATE champions SET lanes = ARRAY['Mid', 'Support'] WHERE name = 'Hwei';
UPDATE champions SET lanes = ARRAY['Top'] WHERE name = 'Illaoi';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Irelia';
UPDATE champions SET lanes = ARRAY['Jungle', 'Support'] WHERE name = 'Ivern';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Janna';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Jarvan IV';
UPDATE champions SET lanes = ARRAY['Top', 'Jungle'] WHERE name = 'Jax';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Jayce';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Jhin';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Jinx';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Kai''Sa';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Kalista';
UPDATE champions SET lanes = ARRAY['Support', 'Mid'] WHERE name = 'Karma';
UPDATE champions SET lanes = ARRAY['Jungle', 'Adc'] WHERE name = 'Karthus';
UPDATE champions SET lanes = ARRAY['Mid'] WHERE name = 'Kassadin';
UPDATE champions SET lanes = ARRAY['Mid'] WHERE name = 'Katarina';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Kayle';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Kayn';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Kennen';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Kha''Zix';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Kindred';
UPDATE champions SET lanes = ARRAY['Top'] WHERE name = 'Kled';
UPDATE champions SET lanes = ARRAY['Adc', 'Mid'] WHERE name = 'Kog''Maw';
UPDATE champions SET lanes = ARRAY['Top'] WHERE name = 'K''Sante';
UPDATE champions SET lanes = ARRAY['Mid', 'Support'] WHERE name = 'LeBlanc';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Lee Sin';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Leona';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Lillia';
UPDATE champions SET lanes = ARRAY['Mid'] WHERE name = 'Lissandra';
UPDATE champions SET lanes = ARRAY['Adc', 'Mid'] WHERE name = 'Lucian';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Lulu';
UPDATE champions SET lanes = ARRAY['Support', 'Mid'] WHERE name = 'Lux';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Malphite';
UPDATE champions SET lanes = ARRAY['Mid', 'Support'] WHERE name = 'Malzahar';
UPDATE champions SET lanes = ARRAY['Support', 'Jungle'] WHERE name = 'Maokai';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Master Yi';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Milio';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Miss Fortune';
UPDATE champions SET lanes = ARRAY['Top', 'Jungle'] WHERE name = 'Mordekaiser';
UPDATE champions SET lanes = ARRAY['Support', 'Jungle'] WHERE name = 'Morgana';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Nami';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Nasus';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Nautilus';
UPDATE champions SET lanes = ARRAY['Mid', 'Support'] WHERE name = 'Neeko';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Nidalee';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Nilah';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Nocturne';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Nunu & Willump';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Olaf';
UPDATE champions SET lanes = ARRAY['Mid', 'Support'] WHERE name = 'Orianna';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Ornn';
UPDATE champions SET lanes = ARRAY['Top', 'Support'] WHERE name = 'Pantheon';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Poppy';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Pyke';
UPDATE champions SET lanes = ARRAY['Mid', 'Jungle'] WHERE name = 'Qiyana';
UPDATE champions SET lanes = ARRAY['Top', 'Jungle'] WHERE name = 'Quinn';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Rakan';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Rammus';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Rek''Sai';
UPDATE champions SET lanes = ARRAY['Support', 'Jungle'] WHERE name = 'Rell';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Renata Glasc';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Renekton';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Rengar';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Riven';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Rumble';
UPDATE champions SET lanes = ARRAY['Mid', 'Top'] WHERE name = 'Ryze';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Samira';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Sejuani';
UPDATE champions SET lanes = ARRAY['Support', 'Adc'] WHERE name = 'Senna';
UPDATE champions SET lanes = ARRAY['Support', 'Adc'] WHERE name = 'Seraphine';
UPDATE champions SET lanes = ARRAY['Top', 'Support'] WHERE name = 'Sett';
UPDATE champions SET lanes = ARRAY['Jungle', 'Support'] WHERE name = 'Shaco';
UPDATE champions SET lanes = ARRAY['Top', 'Support'] WHERE name = 'Shen';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Shyvana';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Singed';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Sion';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Sivir';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Skarner';
UPDATE champions SET lanes = ARRAY['Adc', 'Mid'] WHERE name = 'Smolder';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Sona';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Soraka';
UPDATE champions SET lanes = ARRAY['Support', 'Mid'] WHERE name = 'Swain';
UPDATE champions SET lanes = ARRAY['Mid', 'Jungle'] WHERE name = 'Sylas';
UPDATE champions SET lanes = ARRAY['Mid'] WHERE name = 'Syndra';
UPDATE champions SET lanes = ARRAY['Support', 'Top'] WHERE name = 'Tahm Kench';
UPDATE champions SET lanes = ARRAY['Jungle', 'Mid'] WHERE name = 'Taliyah';
UPDATE champions SET lanes = ARRAY['Mid', 'Jungle'] WHERE name = 'Talon';
UPDATE champions SET lanes = ARRAY['Support', 'Top'] WHERE name = 'Taric';
UPDATE champions SET lanes = ARRAY['Top', 'Support'] WHERE name = 'Teemo';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Thresh';
UPDATE champions SET lanes = ARRAY['Adc', 'Mid'] WHERE name = 'Tristana';
UPDATE champions SET lanes = ARRAY['Top', 'Jungle'] WHERE name = 'Trundle';
UPDATE champions SET lanes = ARRAY['Top', 'Mid'] WHERE name = 'Tryndamere';
UPDATE champions SET lanes = ARRAY['Mid', 'Top'] WHERE name = 'Twisted Fate';
UPDATE champions SET lanes = ARRAY['Adc', 'Support'] WHERE name = 'Twitch';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Udyr';
UPDATE champions SET lanes = ARRAY['Top'] WHERE name = 'Urgot';
UPDATE champions SET lanes = ARRAY['Adc', 'Mid'] WHERE name = 'Varus';
UPDATE champions SET lanes = ARRAY['Adc', 'Top'] WHERE name = 'Vayne';
UPDATE champions SET lanes = ARRAY['Mid', 'Support'] WHERE name = 'Veigar';
UPDATE champions SET lanes = ARRAY['Support', 'Mid'] WHERE name = 'Vel''Koz';
UPDATE champions SET lanes = ARRAY['Mid'] WHERE name = 'Vex';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Vi';
UPDATE champions SET lanes = ARRAY['Jungle', 'Mid'] WHERE name = 'Viego';
UPDATE champions SET lanes = ARRAY['Mid', 'Top'] WHERE name = 'Viktor';
UPDATE champions SET lanes = ARRAY['Mid', 'Top'] WHERE name = 'Vladimir';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Volibear';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Warwick';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Wukong';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Xayah';
UPDATE champions SET lanes = ARRAY['Support', 'Mid'] WHERE name = 'Xerath';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Xin Zhao';
UPDATE champions SET lanes = ARRAY['Mid', 'Adc'] WHERE name = 'Yasuo';
UPDATE champions SET lanes = ARRAY['Mid', 'Top'] WHERE name = 'Yone';
UPDATE champions SET lanes = ARRAY['Top'] WHERE name = 'Yorick';
UPDATE champions SET lanes = ARRAY['Support'] WHERE name = 'Yuumi';
UPDATE champions SET lanes = ARRAY['Jungle', 'Top'] WHERE name = 'Zac';
UPDATE champions SET lanes = ARRAY['Mid', 'Jungle'] WHERE name = 'Zed';
UPDATE champions SET lanes = ARRAY['Adc'] WHERE name = 'Zeri';
UPDATE champions SET lanes = ARRAY['Mid', 'Adc'] WHERE name = 'Ziggs';
UPDATE champions SET lanes = ARRAY['Support', 'Mid'] WHERE name = 'Zilean';
UPDATE champions SET lanes = ARRAY['Mid', 'Support'] WHERE name = 'Zoe';
UPDATE champions SET lanes = ARRAY['Support', 'Mid'] WHERE name = 'Zyra';
UPDATE champions SET lanes = ARRAY['Mid', 'Top'] WHERE name = 'Naafiri';
UPDATE champions SET lanes = ARRAY['Top', 'Jungle'] WHERE name = 'Ambessa';
UPDATE champions SET lanes = ARRAY['Mid', 'Top'] WHERE name = 'Aurora';

-- Fix some special cases or names that might be slightly different in DB
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'Nunu';
UPDATE champions SET lanes = ARRAY['Adc', 'Mid'] WHERE name = 'KogMaw';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'KhaZix';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'RekSai';
UPDATE champions SET lanes = ARRAY['Jungle'] WHERE name = 'BelVeth';
UPDATE champions SET lanes = ARRAY['Top'] WHERE name = 'KSante';
